### ISSUE TITLE
How to download svg format, similar to bwipp-postscriptbarcode?

### ISSUE THREAD

**Issue by mobentec** [metafloor/bwip-js#100]
Hi,

Great work with the server.js—the API functionality is awesome!!

Quick question: We would like to download or view the barcodes in outline / vector format.  Is there a way to not render the .png, but rather, render an svg or eps image?

I noticed that [bwipp's postscriptbarcode](https://github.com/bwipp/postscriptbarcode/wiki/Quick-Guide) [web-based generator](https://the-burtons.xyz/barcode-generator/) outputs eps files, however, how can we get bwip-js's server API to output an eps file?

Your help would be much appreciated.  Thank you!

**Comment by metafloor** [comment]
The current postscript interface layer in bwip-js is designed to rasterize the output.  Changing that logic is a non-trivial task.  I have a good idea how much work is involved as I developed an interface that targets pdf format, but it cheats by embedding the subsetted fonts in the pdf stream.  That work is proprietary and cannot be released.

Generating svg is a feature that I have thought about off and on.  The web and a lot of javascript tooling seem to be moving towards svg more and more.  The hard part as always is the fonts.  The ttf/otf fonts would need to be converted to svg fonts.  That change in font handling plus a significant change in the graphics interface would likely be best implemented as a separate project.  Essentially a vector-based generator as opposed to the current image-based one.

For now, it is just a good idea as I have no time in my schedule to take on a large development task.

**Comment by jpike88** [comment]
@metafloor what about an improvement that just focuses on the actual barcode itself, with no custom/fancy font support? Would that be a simpler thing to accomplish?

**Comment by germanocorrea** [comment]
@jpike88 if you are looking for only barcode (no fonts at all) you can actually create a new Bitmap interface (and call it Vector for some sake) like [this](https://github.com/metafloor/bwip-js/wiki/Integrating-With-Your-Code) wiki article explains, and then you can extend the original BWIPJS class to rewrite **only** the functions that call `bmap.set`, which are, I think, `imagemask` and `drawline`. There is also `show` but it is used to write strings in the barcode. Remember to change the parameters that the `set` function will receive, because you will need two Xs and two Ys.

In the new class, you can actually copy and paste most of the code of those functions and only replace the parts where it calls `bmap.set`, so instead of using x and y for a pixel position, the function need to receive the Xs and Ys of the points that create the vector (which, for our happiness, you only need to extract `bmap.set` out of two nested `for` loops and use the values that these loops are iterating over).

Then, you can actually return the SVG in a buffer, or use some DOM or XML API.

**Comment by jpike88** [comment]
It’s alright, I sucked it up and went for high dpi png. Not that big I spose

**Comment by metafloor** [comment]
The 2.0 release provides a plug-in drawing interface.  And an example SVG drawing object is in the examples directory.  The example even shows how to extract the font paths and embed in the SVG.

**Comment by germanocorrea** [comment]
@metafloor I've seen in the [version 2.0 task list](https://github.com/metafloor/bwip-js/issues/145) that you are planning an output in SVG format, does that mean that in a near future we won't need to manually create methods with the drawing interface for that?
Regardless of that, it's still great that it's not "hacky" anymore to output an SVG, or extend bwip-js to any custom formats, great work!

Only thing, [this README](https://github.com/metafloor/bwip-js/wiki/README-2.0) states that there is an example in the repository, but I'm not being able to find it.

**Comment by metafloor** [comment]
The SVG output will initially be available as an optional "plug-in".  Long term (and hopefully after I get some feedback on it), it may be added to the main dist as a `toSVG()` method.

I will be sync'ing the repository this weekend with the 2.0 release.  That's when the examples will appear.
