### ISSUE TITLE
ISO/IEC 15434 Formats

### ISSUE THREAD

**Issue by SenninSensei** [metafloor/bwip-js#104]
Sorry for my english, im using the library to generate data Matrix barcodes but i need to encode the data in ISO/IEC 15434 Formats using specific header, group separator and trailer, something like:
[)><RS>06<GS>800406141419999960MH80312<GS>21MH80312
<GS>950614141<GS>24099999<RS><EOT>
where [)><RS>06<GS> is the header
<GS> Group separator
<EOT> the End of the Transfer
and so on,
the problem is when i scan the data matrix generated the commands defined above are interpreted as plain text and the scanner throws and error format.

looking for solutions i get to this page https://www.idautomation.com/barcode-faq/mil-std-130-uid-label/

they are replacing the commands <RS> for ASCII characters ~d030, I wonder
if i need to do something similar in this library.

any tips?

**Comment by terryburton** [comment]
By way of example, if the data you want to encode is "[)> **RS** 06 **GS** P100123-01 **GS** 2Prevnum **RS** **EOT**" then you would provide the following input together with the `parse` option which provides syntactic sugar for providing ASCII control characters as escaped, printable characters:

```
[)>^03006^029P100123-01^0292Prevnum^030^004
```

BWIP-JS will automatically spot the opportunity to compress ISO/IEC 15434 structured data wherever the selected symbology supports it. This should be transparent to the application because macro expansion will be performed by the reader during decode, prior to transferring data to the host.

In the case of Data Matrix this invokes the MAC05 and MAC06 codewords for the corresponding ADC media types.

**Comment by SenninSensei** [comment]
it works thx so much
