### ISSUE TITLE
Height and width of data matrix

### ISSUE THREAD

**Issue by tam1111574** [metafloor/bwip-js#109]
Hi there,

Is any way can change correct the height and width (same pixel) of 2D barcode.. ?.. 
I need to create the data matrix with height and weight: 100 x 100 pixel, 147x147 pixel. I change the height and weight of barcode setting but the dimension barcode is not correct.

Thank and best regards.

**Comment by tam1111574** [comment]
I check in your document and  I see BWIPP internally calculates everything in points (72 pts/inch).
if I set create data matrix with  height and width are 50 mm, I will get the barcode with 141 (50*72/25.4) pixel.. But the barcode I received only 132 pixel.. 

This is my testing:
`
const bwipjs = require('bwip-js');

bwipjs.toBuffer({
        bcid:        'datamatrix',       // Barcode type
        text:        '0123456789',    // Text to encode
        scale:       1,               // 3x scaling factor
        height:      50,              // Bar height, in millimeters
	width:       50,
	scaleX: 1,
	scaleY:1,
	margins:     0,
	includetext: false,
	backgroundcolor: 'FFFFFF'
    }, function (err, png) {
        if (err) {
         
        } else {
           console.log("data:image/png;base64," + png.toString('base64'));
        }
    });
`

**Comment by metafloor** [comment]
In general, in order to get a specific size datamatrix barcode, you need to pre-select both the format/size and module width and ensure that the data to be encoded will "fit".  But the sizes you want are almost not possible.  DM barcodes are always an even number of modules (square "dots") both columns and rows.  And the module width is always an even number of pixels, calculated as 2x the scale factor. 

So the 147x147 image size is not possible (there is no DM `format` that can produce it, see: https://github.com/bwipp/postscriptbarcode/wiki/Data-Matrix.)

And the 100x100 image size can only be produced using a 10x10 or 20x20 format, but the 20x20 is not possible as it requires a 5px module width.

So you are limited to targeting a 10x10 format with a 10px module width.  That is not a lot of data, 3 uppercase letters or 6 digits.

To see this in action, change your example to `text: '012345'` and `scale: 5` and remove the width/height parameters.  From the public API:  

http://bwipjs-api.metafloor.com/?bcid=datamatrix&text=012345&scale=5

That generates a 100x100 pixel image.

**Comment by metafloor** [comment]
Always think of something else 5 seconds after hitting the comment button....

You are not limited to integral scale factors, so `scale: 2.5` will produce a 5px module width which means you can use a 20x20 format.  That format can encode a lot more data (almost 4x more).

**Comment by tam1111574** [comment]
Thank you very much Metafloor.. I got some information of data matrix.

**Comment by metafloor** [comment]
I am assuming this issue is resolved.
