### ISSUE TITLE
Add support BWIPP Bar Properties for 2D code (inkspread)

### ISSUE THREAD

**Issue by andrewkip** [metafloor/bwip-js#124]
Hello it would be great to have last BWIPP Bar properties https://github.com/bwipp/postscriptbarcode/wiki/Bar-Properties for DataMatrix.

**Comment by metafloor** [comment]
Unfortunately, this request is not as easy as it should be.  bwip-js is still using an earlier version of the BWIPP matrix renderer, based on the PostScript `imagemask` functionality.  When BWIPP's matrix renderer was upgraded to a use a poly-line-and-fill rendering, it tanked the performance of bwip-js.  Several orders of magnitude slower, with a simple matrix render taking 10s of seconds.

Of course, that was long ago, node 4, maybe even 0.12.  There have been a lot of JIT improvements in v8 since then, and I wonder if I could get the javascript tight enough to maintain performance with the new matrix rendering.

It may also be easy enough to work the new functionality into the existing `imagemask` implementation.  That could serve as a stopgap until I have time to experiment with a better scanline algorithm.

Hi @terryburton:  My understanding is the new inkspread options only effect the disconnected edges of the modules.  No whitespace is created between connected modules.  Is that correct?

**Comment by andrewkip** [comment]
I see. 
And yes  new inkspread options only affect the disconnected edges of the modules.

**Comment by terryburton** [comment]
Sorry for the slow reply.

See here for some explanation and an example:

https://groups.google.com/forum/m/#!topic/postscriptbarcode/xGOhs7rDZ3Q

**Comment by metafloor** [comment]
Terry, thanks for the link.  Those examples make it all clear.

Thinking out loud:

Reviewing the overall drawing logic in the latest version of `renmatrix`, I believe a pure javascript implementation of the graphics primitives used could succeed and be performant; I just don't have time in the foreseeable future to do that work.  But I think the inkspread options are useful, so down the rabbit hole we go with further perverting the current `imagemask` implementation used in bwip-js.

The inkspread logic is pretty straightforward to implement in javascript.  Just need to check the pixel above, below, left and right in the imagemask.  Where an edge is standalone, subtract half the inkspread value of the corresponding h/v parameter.   Since the `imagemask` implementation is already corrupted, I will just replace the unused transform matrix with the values of `inkspreadh` and `inkspreadv`.

Looking at the options unpacking logic, `inkspread` takes precedence over the specific h/v variants, should they be specified together.

@andrewkip:  Let's consider bwip-js's graphics transforms and the inkspread parameters in fractions of a point, where 1pt = 1px at scale=1.  And half the inkspread value is subtracted from a standalone edge.

For an example 0.15 inkspread value, that means 0.075 subtracted.  For that to have any effect on the resulting image, scale would need to be at least 14 due to integer truncation (1 / 0.075 == 13.333).

For an example 0.3 inkspread, 1 / 0.15 == 6.667, so a scale of 7 would be required.  A bit more realistic.  

What scale factors are you using with your datamatrix images?

**Comment by andrewkip** [comment]
3 max 4, may be it is better to input in pixels barcode reduction?

**Comment by metafloor** [comment]
Closing this issue as the 2.0 release is fully in-sync with BWIPP, including the 2d rendering code, so the inkspread options finally work.
