### ISSUE TITLE
backgroundcolor property not working on browser

### ISSUE THREAD

**Issue by chancezeus** [metafloor/bwip-js#133]
When using bwipjs in the browser the backgroundcolor attribute doesn't work correctly, the cause is simple:
- On line 81 of `browser-bwipjs.js` the color is parsed to an integer (using `parseInt(vals.backgroundcolor, 16)`)
- Inside `browser-bitmap.js` lines 50 till 61 the color is treated as a hex string, this of course causes the background color option to fail since it now receives a number, not a hex string
The fix is as simple as removing the `parseInt` and just injecting the raw value as provided.

On a side note, it would be nice (since the browser does support it) to be able to provide a "raw" color value (so full hex string including #, named color, rgb(a) encoded, etc) instead of only a hex string (this allows for example transparency to be used), currently there is no way to have a transparent background in the browser.

**Comment by metafloor** [comment]
Good catch on the `parseInt()` issue.  I will release an update later today for it.

Regarding raw (CSS) color specs:

The original color logic was pulled directly from the BWIPP upstream code, which supports two color spaces, cmyk and rgb, differentiated simply by string length (8 vs 6). Colors can be specified for background (which used to be in the BWIPP code but is now implemented in the Bitmap interface ) and the bar and text colors, which is still implemented in the translated code.  Because of this dual usage, it would only be possible to support CSS color specs for background, which would be awkward.  The translated code needs the actual RGB component values.

Regarding:
> currently there is no way to have a transparent background in the browser

Looks like the browser code (both the demo and browser-bitmap.js) is in need of some love.  The default should be full transparency when a background color is not specified, but the alpha-blending logic is broken.  That fix will also be in today's release.

**Comment by metafloor** [comment]
Finally fixed in the 2.0 release which is pending.
