### ISSUE TITLE
text on top of the barcode

### ISSUE THREAD

**Issue by anvk** [metafloor/bwip-js#134]
My apologies for a silly question, but is there a way to generate barcode text on top of the barcode instead of default location which is at the bottom of it?

Thanks!

**Comment by metafloor** [comment]
The option you are looking for is `textyalign=above`.  The default is `below`.  For example:

https://bwipjs-api.metafloor.com/?bcid=code128&text=0123456789&includetext&textyalign=above&backgroundcolor=ff0000

I spec'd a background color for the example since most browsers are now showing images with a black background (not very useful when the colored part of the image is also black ;-).  For most usage, you likely want a transparent (default) background.

For more information on general bar code options:

https://github.com/bwipp/postscriptbarcode/wiki/Options-Reference

**Comment by anvk** [comment]
Thank you so much for such a detailed answer!
Also big thanks for a great NPM library :)
