### ISSUE TITLE
429 (Too Many Requests)

### ISSUE THREAD

**Issue by flistefliste** [metafloor/bwip-js#169]
After almost 6 months by using the API in production I encounter now a "429 (Too Many Requests)" issue.
Any advice?
![Capture d’écran 2020-07-15 à 11 25 12](https://user-images.githubusercontent.com/6929108/87528507-e4d3de00-c68d-11ea-964e-f6d34f21b942.png)

**Comment by metafloor** [comment]
Unfortunately, yesterday the server was overwhelmed by someone, sending hundreds of requests per second.  I was forced to add rate limiting in order to restore responsiveness.  Presently, it is set at 1 request per second per unique address.

How many requests per second were you sending previously?

**Comment by flistefliste** [comment]
Thanks for your response, 
So far, I have to generate between 1 and 100 barcodes at each requests (maybe a little bit more).
I had to migrate to another provider :(
Let me know

**Comment by metafloor** [comment]
I have reset the server with a rate limit of 10 requests per second per unique address.  I feel that is reasonable.

**Comment by flistefliste** [comment]
No problem, choice is yours, but you may explicit that point on API homepage ;)
