### ISSUE TITLE
Can't this support wkhtmltopdf?

### ISSUE THREAD

**Issue by huangjinshe** [metafloor/bwip-js#174]
I'm trying to use wkhtmltopdf convert html to PDF, but after I tried this, the barcode image never show up in the PDF file.
I did use JS before in HTML, such like `JQuery` all worked fine, no any side effect to convert the HTML to PDF. But I don't know why, this library can't worked.

**Comment by metafloor** [comment]
Since you don't indicate how you are using bwip-js to render the barcodes, I will assume you are rendering them client side to a canvas element.  I suspect the conversion script is firing off before the barcode image has rendered.  You need to execute the conversion to pdf after the images have been loaded/rendered.

**Comment by huangjinshe** [comment]
@metafloor , Thank you, it solved.
