### ISSUE TITLE
Barcode X-Dimension  (Question)

### ISSUE THREAD

**Issue by shailendra121** [metafloor/bwip-js#200]
Hi There,
API is working great for me but couldn't figure out how to set x-dimensions. I am trying to set X Dimension to 0.75mm but couldn't find way to achieve it. Could you please tell me what parameter I should pass to achieve  0.75mm X Dimension (*0.0254)? Here is my current link.

[](https://bwipjs-api.metafloor.com/?bcid=code128&scaleY=5&scaleX=8&text=00093275101964404485&parsefnc&alttext=0009327510196440448%205&eclevel=H&width=20&height=7.5&textsize=5)

**Comment by metafloor** [comment]
If you are displaying on screen/browser at 96dpi / 4dpmm, then .75mm == 3 dots. 

For linear barcodes where module width is mapped to 1pt/1px, that translates to `scale=3`.

For 2d barcodes, it is a bit trickier as module width is either 1 or 2 pt/px.  You will need to adjust as necessary.

**Comment by metafloor** [comment]
Do not set both `width` and `scaleX` - they interact with each other. Use `scale=X` to get the number of pixels you want for module width.  Do not set scaleX/Y unless you are ok with distorted text.

To calculate bar height in mm, it is tricky due to all the different conversions.  Understand that BWIPP internally works in pts, and bwip-js simply maps 1pt to 1px; and html renders at 96dpi.  So you have a multiplier of 96 / 72 / scale.   Assuming `scale=3, that gets you 7.5mm * 96 / 72 / 3 = 3.33mm.   Something along the lines of:

https://bwipjs-api.metafloor.com/?bcid=code128&scale=3&text=00093275101964404485&parsefnc&alttext=0009327510196440448%205&height=3.3

**Comment by shailendra121** [comment]
Thanks for your support. I think we are good with the 1D bar code, the issue is with the QR code. Our QR code contents large string to size is big. X-dimensions with scale 1 is 0.46482 where we need 0.65 minimum. I tried to increase the scale to 2 but then the image size is large. We need to image size should not exceed 40X40 mm.
We set height and width then x-dimensions improving. Could you please help us here. 

https://bwipjs-api.metafloor.com/?bcid=qrcode&text=00093275101964404485%20%20CBAJT00000520TF2&eclevel=H&scale=1

Appreciate your support.

Thanks!

**Comment by metafloor** [comment]
At scale=2, the image is 116x116px.  And 40mm at 96dpi is 151px.  So I would think scale=2 would be a bit too small rather than too large.  Did you mistakenly scale the canvas?

With html rendering at 96dpi, you are never going to get exactly 40mm.  My recommendation would be to use scale=5 to get a 290x290 image, and use css to scale it down 50% (which should minimize distortion).  That will put you at 145px, which is pretty close to 151px.

**Comment by shailendra121** [comment]
Thanks. You mean keep scale 5 and then use image height and width  properties to keep size 40X40 (it could be  between ~40 that is fine)
