### ISSUE TITLE
Adjustable DPI 

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#238]
Hi, is it possible to adjust the DPI of a barcode without scaling the image? (pretty much just increase the resolution)

**Comment by metafloor** [comment]
Most likely not but I cannot understand the question as it doesn't make a lot of sense.  Can you explain more?

**Comment by Jack-Gitter** [comment]
> Most likely not but I cannot understand the question as it doesn't make a lot of sense. Can you explain more?

Sure. The barcodes that I am generating  can be printed, and I wanted the user to be able to adjust the number of dots which would be contained within one inch of the image when printed on a piece of paper.

**Comment by metafloor** [comment]
I do not believe that Chrome, Firefox, et al use the DPI embedded in a PNG image for rendering.  (I experimented with this years ago without success.)  I have always found that images are rendered pixel for pixel.  Where you may have control is using CSS to scale the rendered image down in size.  For example, generate the image at `scale:4` but use CSS to render the image at `scale:25%`.

But I do not expect that to work.  The browsers have moved more and more to WYSIWYG rendering between screen and printer.  To the point where a scaled image on the screen that looks blurry will be identically blurry on the printer.

Please let me know if you find some behavior that is different.

**Comment by mgh128** [comment]
@Jack-Gitter - are you perhaps looking for an output format that is a vector graphic (e.g. SVG, PDF) rather than a bitmap (PNG, JPG).  It's great that there are some examples of this at https://github.com/metafloor/bwip-js/tree/master/examples , though it could be even easier if the demo page at http://bwip-js.metafloor.com/demo/demo.html also provided the options to 'Save as SVG' or 'Save as PDF' alongside 'Save as PNG' and 'Save as JPG', especially when some other online barcode generation tools already provide the option to save as SVG.

**Comment by metafloor** [comment]
Ok, I can take a hint ;-)  Will see what I can code up in the next few days.  Saving as SVG should be possible.  PDF requires too many dependencies to put in a simple demo.
