### ISSUE TITLE
Generating of an incorrect upca barcode.

### ISSUE THREAD

**Issue by dimamarksman** [metafloor/bwip-js#24]
It looks like there is an issue generating upca barcode.
For example `04256212` code will be genarated like a valid upca barcode:
![api-bwipjs rhcloud](https://cloud.githubusercontent.com/assets/3263744/12388941/7adce1ac-bdde-11e5-9630-efeb36faf171.png)

But `04256212 != 042100005622`. Am I not right?

The [link](http://api-bwipjs.rhcloud.com/?bcid=upca&text=04256212&includetext) to the barcode using online generator.

**Comment by terryburton** [comment]
The encoder is recognising that your input is a valid, zero-suppressed GTIN-12 (sometimes referred to as "UPC-E format") and is therefore expanding the input to generate a semantically equivalent UPC-A as follows:

http://stackoverflow.com/a/31539006/2568535

The generator will do the same when asked to create a UPC-E from input that is a compressible GTIN-12 (in "UPC-A format"):

http://stackoverflow.com/a/31079071/2568535

**Comment by dimamarksman** [comment]
Thank you for your explanation.

So library automaticly translates `upc-e` to `upc-a`. 
But in my case I set the type of code `upc-a` and entered value `04256212`. So I would like to see the error because the entered code does not match upc-a pattern (12 digits).

**Comment by terryburton** [comment]
There is no UPC-A/UPC-E pattern, only naïve implementations. By definition UPC-A and UPC-E are variant symbols that encode a GTIN-12 identifier which is either an eight- or twelve-digit number. It would be wrong to restrict the inputs of UPC-A/E to numbers of one length or the other since they represent one and the same data.

In fact, when a standards-compliant barcode scanner reads a UPC-E symbol it transmits a thirteen-digit, EAN-formatted number (the full GTIN-12 converted to GTIN-13 by prefixing `0`)  under the symbology identifier `]E0` which refers to EAN-13, UPC-A and UPC-E. (For completeness, a EAN-8 represents a distinct GTIN-8 identifier and so uses symbology identifier `]E4`.)

If you want to further constrain the length of the input for UPC-A to twelve-digits you would do this in your application.

**Comment by dimamarksman** [comment]
Thank you very much for so detailed answer!
