### ISSUE TITLE
Getting generated Barcode binary

### ISSUE THREAD

**Issue by razzbee** [metafloor/bwip-js#27]
Hello , after the barcode has been generated successfully, we can show it by calling  bw.bitmap().show('canvas', 'N');, is there anyway to get the binary string of the generated image without putting it into canvas first?

**Comment by metafloor** [comment]
There is no predefined method.  But you could hack into lib/canvas.js to provide your own implementation.  Take a look at the Bitmap.show() method.

Note that postscript uses a page-up coordinate space, so (0,0) is in the bottom-left corner. And because font glyphs are not precise rectangles, there can be some pixels with negative x or y coordinates.  That is why you will see Bitmap.show() offset each pixel using the minimum values for x and y.

**Comment by metafloor** [comment]
Please take a look at the new *develop* branch of the project, specifically the `runtest` script which is the test driver for comparing the BWIPP encoding data from ghostscript with the same data from bwipjs.  The test driver compares the encoding data rather than images because there is no way to get pixel perfect matches.

A new "hidden" option has been implemented in bwipjs with version 1.0 that is used to simplify testing.  There is now a global `dontdraw` flag in the cross-compiled code that all three renderers respect.  When set, each renderer returns immediately, leaving the encoding data on the operand stack.  The `true` flag in the following bit of code sets the global dontdraw flag:

```
var bw = new bwipjs(freetype);
try {
    // dontdraw=true
    var stack = bwipp()(bw, "$sym", "$jstext", "$opts", true);
} catch (e) {
```

Normally, the call into BWIPP returns true/success.  When the dontdraw flag is set, it returns what remains on the postscript operand stack (an array), which is the encoding data the renderer(s) didn't consume.  Each entry in the array will be an object with predefined properties.  This bit of code from `runtest` displays the encoding data:

```
for (var i = stack.length-1; i >= 0; i--) {
    var o = stack[i];
    if (o.pixs) { console.log('[' + o.pixs.join(' ') + ']'); }
    if (o.sbs) { console.log('[' + o.sbs.join(' ') + ']'); }
    if (o.bbs) { console.log('[' + o.bbs.join(' ') + ']'); }
    if (o.bhs) { console.log('[' + o.bhs.join(' ') + ']'); }
}
```

`pixs` will be present only for 2D barcodes.  The `sbs`, `bbs` and `bhs` are for linear barcodes.

Take a look at the files in the `tests` directory.  The ones ending `.gsout` where produced by BWIPP/ghostscript, the ones ending `.jsout` where produced by bwipjs.  You will need to understand the different types of data produced for linear barcodes versus 2D, and any barcode with *composite* in its name will have multiple entries, both linear and 2D encodings.

I hope to put up a wiki page on this subject, giving more detail about the format of the encoding data in the next few days.

**Comment by terryburton** [comment]
@metafloor Would a BWIPP debugging option (say "emitintermediateencoding") which emits the codewords, bitstream, etc. that is the result of high-level encoding be of use for complex encoders?

**Comment by metafloor** [comment]
@terryburton  : For bwipjs, the solution in place now is near ideal.  The cross-compiled code can run production or test with the flip of a boolean flag at runtime.  And for testing against BWIPP with ghostscript, the test driver comments-out the renderer bodies, so they behave exactly as the cross-compiled code with the global dontdraw enabled.  This allows me to test even the difficult *composite* symbols that thwarted my previous testing attempts ;-)

So I don't see the need for any change but other front-end maintainers might.

**Comment by metafloor** [comment]
The 2.0 release now has a "raw" option (browser and node.js) that allows extracting the low-level BWIPP encoding/rendering data.  A wiki page is available that describes the data formats [Notes on the Raw BWIPP Data](https://github.com/metafloor/bwip-js/wiki/Notes-on-the-Raw-BWIPP-Data).
