### ISSUE TITLE
Height sizing in what units!?

### ISSUE THREAD

**Issue by Siyfion** [metafloor/bwip-js#31]
Say I create a barcode like so: http://api-bwipjs.rhcloud.com/?bcid=ean8&text=0123456&includetext&guardwhitespace&scale=1&height=100

What the hell height is that supposed to be exactly? It doesn't seem to be inches, mm, cm or pixels... So what is it?!

**Comment by metafloor** [comment]
bwip-js normalizes height to be in millimeters since some barcodes in BWIPP use inches, and others use millimeters.  More importantly, the BWIPP source code uses the Mac concept of pixels/inch, which is 72 (Windows uses 96, not sure where Linux stands...).

If you remove the `includetext` option from the URL (the `height` option is bar height, the text adds to the image height), you will find the height of the barcode to be 283px.  Which is 72 * 100 / 25.4.

**Comment by Siyfion** [comment]
Ah I did wonder if it was some form of mm but with a different conversion unit than I was using... Thanks for the heads-up. :bow:
