### ISSUE TITLE
For React-native!

### ISSUE THREAD

**Issue by umer990** [metafloor/bwip-js#56]
Its seems nice package for Aztec-Code generation!! 

I need this feature for react-native app! Does anyone have idea that how can I use this for react-native!

**Comment by metafloor** [comment]
I am not familiar with react-native but if you know how to bundle a set of javascript files into an RN application, I might be able to help with the glue code.

**Comment by umer990** [comment]
I am trying with some other JavaScript algorithm to integrate in React-native! will get back if can't get succeed!

**Comment by Michaelvilleneuve** [comment]
Hi @metafloor I would love to see this too. I am willing to give it a try.

Could you give me a few directions on how to get started ? 

I only need to generate an image file.
As far as I understood : 
- I need to find a way to load fonts the react native way
- I cannot rely on `require('fs')` since it does not exist on react native
- Therefore I must generate the image differently

What I planned on doing, correct me if I'm wrong : 
- Create a react native folder (will allow to `import bwip from 'bwip-js/react-native'`)
- Copy the node implementation
- Modify fonts imports
- Modify file system calls (write, read, etc)

Thank you for your help !

**Comment by metafloor** [comment]
If you can describe how "binary assets" can be stored in a react-native app, I would definitely be interested in helping.  There must already be a way to store things like image files and fonts used by CSS.

**Comment by Michaelvilleneuve** [comment]
Binary assets, and also fonts/images can be stored directly into the app's native directory dedicated to documents.

There are a few ways to auto link them with a simple command `react-native link` but it only supports fonts. 
I suppose it would be a mandatory step to copy the binaries into iOS and android folders. 

Files can then be read with a library like https://github.com/itinance/react-native-fs
Its API is quite close to `fs.readFileSync`, except it is always async and returns a base64.

**Comment by Ferigit** [comment]
Hi guys, does anybody could find a solution to show aztec format of a barcode in react native? I found some modules for show barcode, but I could not change their format to aztec format!!!

**Comment by Michaelvilleneuve** [comment]
Hi @Ferigit we ended up using bwip-js as a node js server and caching the images on the front side

**Comment by Ferigit** [comment]
Hi @Michaelvilleneuve , thanks for your reply. Did you use this solution? (https://www.npmjs.com/package/bwip-js ). I also tried this solution but I could not import canvas element itself( I do not mean some npm packages like react-native-canvas) to react native, in order to use the mentioned way!. I think you used this solution(http://bwip-js.metafloor.com/). I am a little new to concepts. I appreciate your hints.

**Comment by MUllman** [comment]
anyone figure out how to use this within the app?

**Comment by metafloor** [comment]
@MUllman: what issue are you facing?  Is it just the barcode text that is not printing?  Or something else?

**Comment by MUllman** [comment]
Well the canvas element doesn't exist in react native. There are packages like [react-native-canvas](https://github.com/iddan/react-native-canvas) but when I use that and pass in that canvas nothing gets rendered and there are no errors, Im not sure what exactly is going wrong.

**Comment by metafloor** [comment]
Are you running node.js on the backend and can you use the node interface that renders a png file? I have never used react-native so I am not sure if that is possible....

One other thought:  I have used pako.js in other projects as a browser-based zlib.  With pako, it is possible to create a png file in the browser.  Would that would work with react-native?  The output would be a Uint8Array containing the png image.
