### ISSUE TITLE
Error: array-marker-not-found

### ISSUE THREAD

**Issue by efrainx3** [metafloor/bwip-js#57]
Good day,
I'm trying to use the API, but the site responds with an error "Error: array-marker-not-found".
I want to generate the following bar code: http://api-bwipjs.rhcloud.com/?bcid=gs1-128&text=61312350510&includetext&textsize=6&textyoffset=1&scaleX=2

I'm doing something wrong?

Thanks for the help.

**Comment by metafloor** [comment]
Looks like a bug in the cross-compiler.  Haven't had one of those in while....

I will try to track it down this evening.

**Comment by metafloor** [comment]
The 1.2.0 release introduced a bug that was not caught by the test framework, so that raises yet another issue.  But that is not the problem here.

If I put the provided text into the BWIPP online barcode generator, it also generates a runtime error.  So BWIPP and bwip-js agree.  Your input text is not valid.  GS1-128 requires each data segment to be prefixed with an application-id, delimited by parens.

So the solution for your specific case is to either add an application-id, or use the **code128** symbol, which does not use app-ids.

Regardless, there is a bug in the v1.2.0 release which everyone should replace with v1.2.1.  (Even after all this time, I still cannot think in PostScript...)
