### ISSUE TITLE
pdf417 params

### ISSUE THREAD

**Issue by quicksoftpro** [metafloor/bwip-js#65]
Can you please help me pass these params when generating pdf417 bar codes?
I do not see a documentation for the same.

here is what I got as params : 
XDim = 0.02
YDim = 0.03
Bar Height = 0.30
Aspect = 0.25
Columns = 18 or 16
Rows = 0
ECC = 4
Containment area is about 1000 X 5000 pixels

This is how I am trying to run it.
bwipjs.toBuffer({
        bcid:        'pdf417',       // Barcode type
        text:        text,    // Text to encode                  
        height:      0.3,              // Bar height, in millimeters
        includetext: false,
        xdim : 0.02,
        ydim: 0.03,
        aspect: 0.25,
        columns: 18,
        rows:0

    }, function (err, png) {

**Comment by metafloor** [comment]
Have you looked at the BWIPP pdf417 documentation?  Why do you think there are `aspect`, `xdim` and `ydim` parameters?  Here is the documentation for pdf417:

https://github.com/bwipp/postscriptbarcode/wiki/PDF417

I suggest you use the bwip-js Online Barcode Generator (from the bwip-js project page):

http://bwip-js.metafloor.com/demo/demo.html

Select PDF417 and play with the parameters until you get the barcode shape/size you are looking for.

Regarding `aspect`, is that the shape of each bar module or overall symbol size.  If bar module, then you likely want `rowmult=4` to give you a bar module that is 4x tall as wide.

Regarding `height=0.3`.  For 2d symbols, that is symbol height, not bar height.  I don't recommend using that option since you want to separately control module height.  Setting `height` will scale the symbol to the specified height:

With just `rowmult=4`:  

![rowmult=4](http://api-bwipjs.rhcloud.com/?bcid=pdf417&text=This%20is%20PDF417&columns=2&rowmult=4)

With `rowmult=4 height=25.4`: 

![height also](http://api-bwipjs.rhcloud.com/?bcid=pdf417&text=This%20is%20PDF417&columns=2&rowmult=4&height=25.4)
