### ISSUE TITLE
Update to BWIPP 2017-04-03 (support for the GS1 North American Coupon)

### ISSUE THREAD

**Issue by sbatch24** [metafloor/bwip-js#70]
Hi,
Could we please merge the 2017-04-03 release of bwipp and add the option to render the new `gs1northamericancoupon` with options?
Thanks!

**Comment by metafloor** [comment]
Working on it.  Terry added a new postscript operator to the latest error handling so a bit of extra work for this one.

**Comment by sbatch24** [comment]
Very much appreciated!

**Comment by metafloor** [comment]
The new version is working but I have had to comment out some code in barcode.ps due to a cross-compiler issue.  There is a variable in the new postscript code that cannot be traced and I am not sure if it is a compiler error or issue with the new `renmatrix`.  But here's what it looks like so far:

![image](https://cloud.githubusercontent.com/assets/385436/24669858/2c2f7e1e-1929-11e7-81de-b83aa7f16c68.png)

I'm holding off on the release until the compiler issue is resolved.

**Comment by metafloor** [comment]
Please verify the new release is working as expected.

**Comment by sbatch24** [comment]
We're able to run on node and verify this is working as expected. Thanks again!

**Comment by metafloor** [comment]
Thanks for the feedback.  Closing this out.
