### ISSUE TITLE
Upgrade to BWIPP 2017-06-09

### ISSUE THREAD

**Issue by p2k** [metafloor/bwip-js#78]
Very recently, BWIPP was updated to [2017-06-09](https://github.com/bwipp/postscriptbarcode/releases/tag/2017-06-09). It fixes a DataMatrix encoding issue which I've [reported there](https://github.com/bwipp/postscriptbarcode/issues/86) since it is technically not a bug of bwip-js itself. However, in order to test it in our application, we'd need the fix in this library. If you could give your code translator a quick nudge, we'd appreciate it.

**Comment by metafloor** [comment]
bwip-js is updated on npm with the latest BWIPP, minus the new dotcode renderer.  There is a postscript construct in there that the cross-compiler didn't understand and needs to be investigated.

**Comment by terryburton** [comment]
On 10 Jun 2017 21:00, "metafloor" <notifications@github.com> wrote:

bwip-js is updated on npm with the latest BWIPP, minus the new dotcode
renderer. There is a postscript construct in there that the cross-compiler
didn't understand and needs to be investigated.

Don't break your back on DotCode yet as the implementation isn't really
ready for prime time. I'm just out of focused time on this so pushed what I
have.

I've done just enough to allow me to give quality feedback on the public
draft of the specification and for others to verify my low level symbol
construction. I've yet to implement optimised encoding (the spec may change
before being accepted by ISO/IEC) and you'll notice that it uses the matrix
renderer rather than plot dots.

**Comment by p2k** [comment]
I'm fine with the DataMatrix fix right now. This closes the issue for me. Thank you for your effort!
