### ISSUE TITLE
bwipjs memory usage 16mb for freetype

### ISSUE THREAD

**Issue by terrancesnyder** [metafloor/bwip-js#79]
Hello all. Is there any chance we can reduce the footprint in memory of bwipjs. We currently see that freetype.js (i assume for rendering characters on the barcode) is being used and that it is taking 16.7mb of space in ram.

We run embedded devices and our total application space is 90mb with bwipjs. It would be amazing if we could reduce the size form 90mb even further down and currently freetype is the long poll in the tent at taking ~20% of the memory usage.

We have opentype.js being used in our app, and that has a deferred font loading process and has a lower footprint the opentype. Any thoughts on if something can be optimized here?
![capture](https://user-images.githubusercontent.com/379950/27004827-8a0257a2-4dde-11e7-8cf1-c0ba6af6a337.PNG)

**Comment by metafloor** [comment]
I am getting less and less enthralled with the enscriptem-compiled freetype module as time moves on.  It does not play well with others (the source of several open issues with bwip-js) and as you have noticed, it has a massive memory and code footprint.  Unfortunately, there is nothing I can do about it.  

I have not looked at opentype.js since at least a year and half ago.  Back then, it was missing functionality that was needed by bwip-js.  Looking at the commit log, I see that some of the issues may have been addressed.  I will look into whether it can replace freetype.

I cannot commit to any kind of time frame at this point.  I am slammed at work and don't have time for a side project right now.  Since you are actively using opentype.js, would you be willing to help out?  I can quickly spec the interface that bwip-js needs for font rendering.

**Comment by bpetty-formfast** [comment]
For the barcodes we are using, freetype is not required at all yet bwip-js forces its use.  To get around this I made a simple modification to the BWIPJS constructor so that if freetype is undefined, I don't set this.ft.  Now I don't have to distribute that monstrosity, load times are improved, and everything still works.  I would highly recommend breaking the reliance on any font library.

**Comment by metafloor** [comment]
I have a replacement for freetype that is testing stable.  This new approach makes no-freetype the default; to use freetype, a function call is available to enable it.  And generating bar codes with no text will incur no extra memory pressure.  

I am rolling in one other improvement on memory allocation that is still in development, so these changes will likely not be committed until this weekend.

**Comment by rhclayto** [comment]
Any closer to a commit? Many thanks!

**Comment by metafloor** [comment]
Almost there.  Updating documentation as this will likely cause some headaches for people who have customized their usage of bwip-js.  I still need to test against a React app as one of my goals of this release is to get browser-implemented `require()` to work correctly.  (I think that is were react et al. were having issues with `freetype.js`.)

I am considering pushing to the master branch without publishing on npm if there are any node developers that are willing to be guinea pigs ;-)  Hosting in a browser will still need to wait.

**Comment by metafloor** [comment]
Version 1.5 is out with the freetype replacement.  Please let me know how it works for you.

**Comment by metafloor** [comment]
Closing as resolved.
