### ISSUE TITLE
Calculate Width and heigth in Pixel

### ISSUE THREAD

**Issue by JonathanGonczoroski** [metafloor/bwip-js#82]
I would like to generate the width value of 800 pixel and the height value of 10 pixel. These values in millimeters are 211.6666 and 2.6458. But when it generates the image, it has a pixel of 1060 pixel and 14 pixel. What is wrong ?

```javascript

bwipjs.toBuffer({
    bcid: 'code128',
    text: '01asdasdasdasdasdasdasdasdasdasdasdadasd23456789',
    width: 211.6666,
    height: 2.6458,
}, function (error, png) {
    let outFile = path.join(DIR_IMAGES, 'barcode.png');
    fs.writeFile(outFile, png, function (error) {
        if (error) {
            console.log(error);
        } else {
            console.log('deu');
        }
    })
});
```

**Comment by metafloor** [comment]
It is not possible to generate low-resolution bar codes to an exact pixel width.  They do not scale linearly but in quantized multiples of their base module width.  If a bar code is X pixels at `scale=1`, it will be 2X pixels at `scale=2` and so on.  And it will never be any size in between those multiples.

That applies only to low-resolution images, which is what bwip-js is designed and optimized to produce.  At higher resolutions, 300dpi and above, it is possible to adjust the individual widths of the bars and spaces to achieve a close match to the desired width while still keeping the symbol within spec.  This is what BWIPP, the upstream source code used by bwip-js, does with its PostScript-based drawing.

Finally, to answer another point in your query, the `width` parameter and all other dimensional parameters like font size and padding are normalized at `scale=1`.  By not specifying a scaling factor in your options, you get the default `scale=2`.  That is why the image is larger than you expect, but not twice as large due to the quantized size changes.

**Comment by metafloor** [comment]
One extra comment regarding the height of the bar code (which also applies to width).  BWIPP internally calculates everything in points (72 pts/inch or 2.83 pts/mm) and bwip-js maps one point to one pixel.  So 2.6458mm -> 2.6458 * 72 / 25.4 -> 7.499 pixels, resulting in floor(7.499) = 7 at `scale=1`.
